### ISSUE TITLE
Something wrong with the receipt?

### ISSUE THREAD

**Issue by gijscor** [remarcmij/JavaScript2_examples#1]
I was just thinking, if you bought 2 books, why is there only 1 item with 6% BTW on the receipt and 2 with 21%?

**Comment by remarcmij** [comment]
Yes, that puzzled me too. But I came to the conclusion that the numbers do not represent the number of items in each BTW category but a code for the BTW category itself (1 = low, 2 = high). That interpretation seems to match the calculations. Next time I'll buy three books 😁.

**Comment by remarcmij** [comment]
I've blacked out the confusing numbers.

**Comment by gijscor** [comment]
@makes sense, thanks for solving this mystery for me!
